// <auto-generated />
using System;
using AuthAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009123428_AccountSettings")]
    partial class AccountSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthAPI.Models.BodyMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Belly")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BfPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Biceps")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BicepsLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BicepsRight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Calf")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CalfLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CalfRight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Chest")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ForearmLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ForearmRight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Hips")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Neck")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Shoulders")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Thigh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ThighLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ThighRight")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Vtaper")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Waist")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Whr")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("BodyMeasurements");
                });

            modelBuilder.Entity("AuthAPI.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("CurrentWeight")
                        .HasColumnType("numeric");

                    b.Property<int?>("DefaultRestTimerSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DefaultWeightIncrement")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Goal")
                        .HasColumnType("text");

                    b.Property<decimal?>("Height")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JobType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ManualCaloricTarget")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ManualCarbsG")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ManualFatG")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ManualProteinG")
                        .HasColumnType("numeric");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
